FROM ruby:3.3

RUN apt-get update -qq && apt-get install -y build-essential git

WORKDIR /usr/src/app/myJekilApp

COPY docker/entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

RUN gem install bundler

EXPOSE 4000

CMD ["/usr/src/app/entrypoint.sh"]